### ISSUE TITLE
我的第一篇博客 - Hexo

### ISSUE THREAD

**Issue by apple6186** [apple6186/gittalk-comments#2]
https://blog.bytelong.org/2024/11/06/%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E7%AF%87%E5%8D%9A%E5%AE%A2/ 

 #我于2024//11/6搭建好了自己的博客网站，后面会对其进行更改 （0.0）##11.7–加入了网站评论功能–使用gittalk评论插件来实现过程##1.创建Github OAuth 应用###1.打开Github并点击个人头像下划找到setting##2.问题homepage URL：the URL to your application homepage 不想

**Comment by apple6186** [comment]
hih

**Comment by Ringyuki** [comment]
我草6666666
![mashiro](https://img-static.hikarinagi.com/uploads/2024/11/d2b5ca33bd20241105110054.png "mashiro")
